"""empty message

Revision ID: 1c824db3bcd9
Revises: 5ce90244ec82
Create Date: 2021-10-14 19:39:30.403314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c824db3bcd9'
down_revision = '5ce90244ec82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paycheck',
    sa.Column('paycheck_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('contract_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('paycheck_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paycheck')
    # ### end Alembic commands ###
