"""empty message

Revision ID: 5ce90244ec82
Revises: cfcb1fa309c5
Create Date: 2021-10-13 20:47:35.085150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce90244ec82'
down_revision = 'cfcb1fa309c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('contract',
    sa.Column('contract_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('contract_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_table('work_role',
    sa.Column('work_role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('hour_budget', sa.Numeric(), nullable=True),
    sa.Column('hourly_pay', sa.Numeric(), nullable=True),
    sa.Column('hourly_deduction', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.contract_id'], ),
    sa.PrimaryKeyConstraint('work_role_id'),
    sa.UniqueConstraint('contract_id')
    )
    op.create_table('time_worked',
    sa.Column('time_worked_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_role_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('date_worked', sa.Date(), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('hours_worked', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['work_role_id'], ['work_role.work_role_id'], ),
    sa.PrimaryKeyConstraint('time_worked_id'),
    sa.UniqueConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_worked')
    op.drop_table('work_role')
    op.drop_table('contract')
    op.drop_table('client')
    # ### end Alembic commands ###
