"""empty message

Revision ID: 8ec98a77f252
Revises: f4d636475d8c
Create Date: 2021-10-28 19:33:45.223316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec98a77f252'
down_revision = 'f4d636475d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workrole_contract_id_key', 'workrole', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('workrole_contract_id_key', 'workrole', ['contract_id'])
    # ### end Alembic commands ###
