"""empty message

Revision ID: f4d636475d8c
Revises: 
Create Date: 2021-10-28 15:39:25.694960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d636475d8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('employee',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('ssn', sa.String(length=9), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('paycheck',
    sa.Column('paycheck_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('contract_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('paycheck_id')
    )
    op.create_table('contract',
    sa.Column('contract_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('contract_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_table('user_account',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workrole',
    sa.Column('workrole_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('workrole_description', sa.Text(), nullable=True),
    sa.Column('hour_budget', sa.Numeric(), nullable=True),
    sa.Column('hourly_pay', sa.Numeric(), nullable=True),
    sa.Column('hourly_deduction', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.contract_id'], ),
    sa.PrimaryKeyConstraint('workrole_id'),
    sa.UniqueConstraint('contract_id')
    )
    op.create_table('employee_workrole',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('workrole_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['workrole_id'], ['workrole.workrole_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'workrole_id')
    )
    op.create_table('time_worked',
    sa.Column('time_worked_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('workrole_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('date_worked', sa.Date(), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('hours_worked', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['workrole_id'], ['workrole.workrole_id'], ),
    sa.PrimaryKeyConstraint('time_worked_id'),
    sa.UniqueConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_worked')
    op.drop_table('employee_workrole')
    op.drop_table('workrole')
    op.drop_table('user_account')
    op.drop_table('contract')
    op.drop_table('paycheck')
    op.drop_table('employee')
    op.drop_table('client')
    # ### end Alembic commands ###
