"""empty message

Revision ID: a78323f03826
Revises: dd4186791c28
Create Date: 2021-10-27 20:10:38.150685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78323f03826'
down_revision = 'dd4186791c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_role', sa.Column('workrole_description', sa.Text(), nullable=True))
    op.drop_column('work_role', 'contract_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_role', sa.Column('contract_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('work_role', 'workrole_description')
    # ### end Alembic commands ###
