"""empty message

Revision ID: 1694eeb91f79
Revises: 1c824db3bcd9
Create Date: 2021-10-17 17:59:04.897702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1694eeb91f79'
down_revision = '1c824db3bcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_work_role',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_role_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['work_role_id'], ['work_role.work_role_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'work_role_id')
    )
    op.drop_constraint('employee_user_id_key', 'employee', type_='unique')
    op.drop_column('employee', 'user_id')
    op.alter_column('paycheck', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('paycheck', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('paycheck', 'contract_description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paycheck', 'contract_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('paycheck', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('paycheck', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('employee', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('employee_user_id_key', 'employee', ['user_id'])
    op.drop_table('employee_work_role')
    # ### end Alembic commands ###
